title: Evan's Portfolio # your name (or website title) here
logo: "/images/headshot_2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm a data scientist and aspiring ML engineer. I just graduated from the University of Maryland in May, 2024 with a B.S. in Computer Science and Physics. I'm passionate about extracting useful trends from data and enjoy learning about new Computer Vision and NLP research.
  <br><br>
  I'm currently performing DS & front-end software engineering at NAVAIR.
  <br><br>
  I built this portfolio to display my skills and interests efficiently and aesthetically. As I'm in the early stages of creating this portfolio, most content is missing and/or needs refinement, but please look around at what I do have so far! 
  <br><br>
  <a href="/pdf/Evan_McClintock_Resume_24-06.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/evan-mcclintock-25622a19a/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-WDXSEV2WPQ
